server.port=8080
spring.application.name=apiservice

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# Ruta productos
spring.cloud.gateway.routes[0].id=productoservice
spring.cloud.gateway.routes[0].uri=lb://productoservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/productos/**

# Ruta ordenes
spring.cloud.gateway.routes[1].id=ordernservice
spring.cloud.gateway.routes[1].uri=lb://ordernservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/ordenes/**

# Ruta pagos
spring.cloud.gateway.routes[2].id=pagoservice
spring.cloud.gateway.routes[2].uri=lb://pagoservice
spring.cloud.gateway.routes[2].predicates[0]=Path=/pagos/**