spring.application.name=pagoservice

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.data.mongodb.uri=mongodb://admin:admin123@host.docker.internal:27017/admin

# Bootstrap server - usa kafka:29092 en Docker (vÃ­a ENV), localhost:9092 en local
spring.kafka.bootstrap-servers=localhost:9092

# --- Producer ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.pagos=pagos-topico

# Forzar a Kafka a fallar rÃ¡pido si no hay red (3000 ms = 3 segundos)
spring.kafka.producer.properties.max.block.ms=3000
spring.kafka.producer.properties.request.timeout.ms=3000
spring.kafka.producer.properties.delivery.timeout.ms=3000